Task_1_1_1
gikipil/o pull request #7
Opened 2022-11-08 17:36 UTC by gikipil

2022-11-09 03:48 UTC, shadrina requested changes
Папку `.gradle` не нужно добавлять в гит. Ее надо заигнорить и удалить.

p.s. В прошлом пул реквесте кстати такой проблемы почему-то не было, она появилась в этом.

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        System.out.println("Создан массив: 1,5,3,9,12,6,33");
Вот это можно убрать

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        System.out.println("Массив успешно отсортирован!");
И вот это можно убрать

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        System.out.println("Массив успешно отсортирован!");
По всему файлу

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        System.out.println("Массив успешно отсортирован!");
Ну либо, если очень хочется, можно это оставить это для первой лабы и просто больше так не делать

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    void sort2() {
Вот у тебя выше есть замечательный комментарий, который можно убрать и всю необходимую информацию о тесте уместить в название теста: например, `repeatedElementsArrayTest()`.

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    void sort2() {
Номер теста не несет полезной информации, тем более что их порядок не важен.

2022-11-09 03:48 UTC, shadrina commented on Task_1_1_1/src/main/java/org/example/Heapsort.java
> +    public static int[] sort(int [] arr) {
Если метод не умещается в экран, его лучше разбить на вспомогательные методы.

2022-11-09 03:53 UTC, gikipil commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    void sort2() {
Он ругался на отсутствие комментариев

2022-11-09 06:56 UTC, shadrina requested changes

2022-11-09 06:56 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    void repeatedElementsArrayTest() {
`java.util.Random`

отсортировать своим методом и методом из стандартной библиотеки и сравнить результаты

2022-11-16 06:06 UTC, shadrina approved these changes

2022-11-16 06:13 UTC, merged