Task-1-2-1
gikipil/o pull request #8
Opened 2022-11-24 17:24 UTC by gikipil

2022-11-29 14:10 UTC, shadrina commented
Правильно сделал, что удалил `.gradle` в предыдущей лабе, только давай это сделаем в отдельном PR, не здесь. И можешь без апрува его залить.

2022-11-29 14:10 UTC, shadrina commented
Рано похвалила... Ты тут полностью удаляешь код первой лабы, так делать не надо.

2022-11-29 14:11 UTC, shadrina requested changes

2022-11-29 14:11 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +public class Stack {
Стек нужно сделать параметризованным, `Stack<T>`

2022-11-29 14:11 UTC, shadrina commented on Task_1_2_1/src/test/java/StackTest.java
> +        System.out.println("Successfully completed");
С этой лабы давай без этого...

2022-12-08 11:55 UTC, shadrina requested changes
1. Ты все еще удаляешь код первой лабы
2. Нерешенный варнинг от reviewdog'а

2022-12-08 11:56 UTC, gikipil commented
Я не знаю как не удалять 1 задачу она сама добавляется в каждый бранч

2022-12-08 12:06 UTC, shadrina commented
Она должна присутствовать в каждом очередном бранче от мастера, потому что она часть мастера. Ее удалять как раз не надо. Чтобы все сработало, надо отбранчеваться от мастера и не трогать эту папку, а заливать все в новую.

2022-12-09 05:19 UTC, closed without merging